on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gebareg.azurecr.io
        username: ${{ secrets.acr_gebareg_username }}
        password: ${{ secrets.acr_gebareg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t gebareg.azurecr.io/clugitops:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push gebareg.azurecr.io/clugitops:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clugitops_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clu-gitopsbbfd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clu-gitopsbbfd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clu-gitopsbbfd
        container-registry-url: gebareg.azurecr.io
        container-registry-username: ${{ secrets.acr_gebareg_username }}
        container-registry-password: ${{ secrets.acr_gebareg_password }}
        secret-name: clugitopsdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clu-gitopsbbfd
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gebareg.azurecr.io/clugitops:${{ github.sha }}
        imagepullsecrets: |
          clugitopsdockerauth
