name: Sample workflow

on:
 workflow_dispatch

env:
  SERVER: abc
  CLOUD: Azure

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job Number One
    steps:
      - name: Say Hello
        env:
          USERNAME: Geert
        run: |
          echo Hello $USERNAME, welcome to $CLOUD
      - name: Say Hello Again
        run: echo Hello Again
  job2:
    runs-on: ubuntu-latest
    name: Job Number Two
    steps:
      - name: Hello from Job 2
        run: echo Hello from Job 2
  job3:
    runs-on: ubuntu-latest
    needs: job1
    if: always() # job depends on job 1 but should always run
    steps:
      - name: Hello from Job 3
        run: echo Hello from Job 3

