name: Sample workflow

on:
 workflow_dispatch

env:
  SERVER: abc
  CLOUD: Azure

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Job Number One
    env:
      MESSAGE: Variable available to all steps in the job
    steps:
      - id: step1
        name: Say Hello
        env:
          USERNAME: Geert
        run: |
          echo Hello $USERNAME, welcome to $CLOUD
          echo "::set-output name=message::Hello $USERNAME"
          echo $MESSAGE
      - name: Say Hello Again
        run: echo Hello Again
    outputs:
      # available to all dependent jobs; see job3 below
      output1: ${{ steps.step1.outputs.message }}
  job2:
    runs-on: ubuntu-latest
    name: Job Number Two
    steps:
      - name: Hello from Job 2
        run: echo Hello from Job 2
  job3:
    # no name; name will be job id job3
    runs-on: ubuntu-latest
    needs: job1
    if: always() # job depends on job 1 but should always run
    steps:
      - name: Hello from Job 3
        run:  | 
          echo Hello from Job 3
          echo ${{ needs.job1.outputs.output1 }}
  job4:
    name: Job with environment
    environment: test  # create environment in settings and set reviewers and or timer
    runs-on: ubuntu-18.04
    steps:
      - name: Hello from job 4 with environment
        run: echo Hello from job 4

